import { useUser } from '@auth0/nextjs-auth0'
import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/HomePage/Footer'
import NavBar from '../components/HomePage/NavBar'
import NewPostForm from '../components/HomePage/NewPostForm'

const Home: NextPage = () => {
  const {user} = useUser();
  return (
    <>
      <Head>
        <html data-theme="business" ></html>
        <title>Screamer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {user ? <NewPostForm /> : null}

      <Footer />
    </>
  )
}

export async function getServerSideProps() {
  const posts = await axios.get("/api/posts");
  return {
      props: {
          posts
      }
  }
}

export default Home
